
Vagrant.configure("2") do |config|

  # WEB 1
  config.vm.define "web1" do |web1|
    web1.vm.box = "ubuntu/trusty64"
    web1.vm.hostname = "webserver1"
    web1.vm.network "private_network", ip: "192.168.1.201"
    
    web1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
    end

  end

  # WEB 2
  config.vm.define "web2" do |web2|
    web2.vm.box = "ubuntu/trusty64"
    web2.vm.hostname = "webserver2"
    web2.vm.network "private_network", ip: "192.168.1.202"
    
    web2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--cpus", 1]
    end
  end
  
  
end
